const express = require("express");
const app = express();
const helmet = require("helmet");
const xss = require("xss-clean");
const trainrouter = require("./routes/trainrouter");
app.use(helmet());
app.use(express.json());
app.use(xss());
app.use("/train", trainrouter);
module.exports = app;
